CREATE TABLE items
(
    id INT AUTO_INCREMENT NOT NULL COMMENT 'ID',
    parent_id INT NOT NULL COMMENT '親の ID（なければ 0）',
    name VARCHAR(512) NOT NULL COMMENT '名称',
    url VARCHAR(512) COMMENT 'フォルダの場合は NULL',
    orders INT NOT NULL COMMENT '順序',
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    deleted DATETIME COMMENT '削除日時',
    PRIMARY KEY (id)
) COMMENT 'ブックマークとフォルダ情報';
