CREATE TABLE notifications
(
    id INT AUTO_INCREMENT NOT NULL COMMENT 'ID',
    title VARCHAR(512) NOT NULL COMMENT 'タイトル',
    subject TEXT NOT NULL COMMENT '本文',
    url VARCHAR(512) NULL COMMENT '遷移先',
    target_premium TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'プレミアム限定フラグ',
    target_date DATETIME COMMENT '配信開始日時',
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    deleted DATETIME COMMENT '削除日時',
    PRIMARY KEY (id)
) COMMENT 'お知らせ情報';
