CREATE TABLE users
(
    id INT AUTO_INCREMENT NOT NULL COMMENT 'ID',
    uid VARCHAR(256) COMMENT 'Google UID',
    email VARCHAR(512) NOT NULL COMMENT 'EMail',
    fcm_token VARCHAR(256) COMMENT '配信トークン',
    user_hash VARCHAR(256) COMMENT 'JWT に含める hash 値',
    premium TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'プラミアムフラグ',
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    deleted DATETIME COMMENT '削除日時',
    PRIMARY KEY (id)
) COMMENT 'ユーザー情報';
