name: release

on:
  push:
    tags:
      - 'cron-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Set Up GCP Auth
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: cron setUp
      run: gcloud app deploy yaml/cron.yaml

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: good
        SLACK_MESSAGE: 'Post cron :rocket:'
        SLACK_TITLE: cron setUp Success
        SLACK_USERNAME: GitHub Actions
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
