name: release

on:
  push:
    tags:
      - 'cron-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set Up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: cron setUp
      run: gcloud app deploy yaml/cron.yaml

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: good
        SLACK_MESSAGE: 'Post cron :rocket:'
        SLACK_TITLE: cron setUp Success
        SLACK_USERNAME: GitHub Actions
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
