name: pr-test

on:
  pull_request:
    branches:
      - 'master'
  pull_request_target:
    branches:
      - 'master'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Docker start
      run: docker-compose up -d test-db

    - name: build
      run: ./gradlew clean test

    - name: Docker stop
      run: docker-compose stop