name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set Up GCP Auth
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Setup secrets
      run: |
        echo "${{ secrets.VPC_ACCESS_CONNECTOR }}" | base64 -d >> app.yaml
        echo "${{ secrets.SECRET_YAML }}" | base64 -d > secret.yaml

        VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
        sed -i -e 's/version_code/$VERSION/g' ext.gradle
        sed -i -e 's/project_id/${{ secrets.GCP_PROJECT_ID }}/g' ext.gradle

    - name: appengineDeploy
      run: ./gradlew clean appengineDeploy

    - name: Slack Notification Success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_COLOR: good
        SLACK_ICON: ${{ secrets.SLACK_ICON_URL }}
        SLACK_MESSAGE: "Success Build\\nhttps://github.com/bvlion/ShareBookmarksApi/commit/${{ github.sha }}\\nhttps://github.com/bvlion/ShareBookmarksApi/actions/runs/${{ github.run_id }}"
        SLACK_TITLE: Deploy Success
        SLACK_USERNAME: GitHub Actions
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Slack Notification Failure
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_COLOR: danger
        SLACK_ICON: ${{ secrets.SLACK_ICON_URL }}
        SLACK_MESSAGE: "Success Build\\nhttps://github.com/bvlion/ShareBookmarksApi/commit/${{ github.sha }}\\nhttps://github.com/bvlion/ShareBookmarksApi/actions/runs/${{ github.run_id }}"
        SLACK_TITLE: Deploy Failure
        SLACK_USERNAME: GitHub Actions
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
